/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ryansPC
 */
import javax.swing.*;

public class AccountingGUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountingGUI
     */
    public AccountingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuBar11 = new javax.swing.JMenuBar();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuBar12 = new javax.swing.JMenuBar();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuBar13 = new javax.swing.JMenuBar();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenuBar14 = new javax.swing.JMenuBar();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenuBar15 = new javax.swing.JMenuBar();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenuBar16 = new javax.swing.JMenuBar();
        jMenu30 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenuBar17 = new javax.swing.JMenuBar();
        jMenu32 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenuBar18 = new javax.swing.JMenuBar();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenuBar19 = new javax.swing.JMenuBar();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenuBar20 = new javax.swing.JMenuBar();
        jMenu40 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenuBar21 = new javax.swing.JMenuBar();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenuBar22 = new javax.swing.JMenuBar();
        jMenu44 = new javax.swing.JMenu();
        jMenu45 = new javax.swing.JMenu();
        jMenuBar23 = new javax.swing.JMenuBar();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenuBar24 = new javax.swing.JMenuBar();
        jMenu48 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();
        jMenuBar25 = new javax.swing.JMenuBar();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenuBar26 = new javax.swing.JMenuBar();
        jMenu52 = new javax.swing.JMenu();
        jMenu53 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        TextFieldAccountNumber1 = new javax.swing.JTextField();
        jTextFieldAccountName = new javax.swing.JTextField();
        jTextFieldAccountAdress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextFieldAccountNumber2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TextFieldAccountNumber4 = new javax.swing.JTextField();
        TextFieldAccountNumber3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTransaction1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        TextFieldAccountNumber5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar6.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar6.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar7.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar7.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar8.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar8.add(jMenu14);

        jMenu15.setText("jMenu15");

        jMenuItem1.setText("jMenuItem1");

        jMenu16.setText("File");
        jMenuBar9.add(jMenu16);

        jMenu17.setText("Edit");
        jMenuBar9.add(jMenu17);

        jMenu18.setText("File");
        jMenuBar10.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar10.add(jMenu19);

        jMenu20.setText("File");
        jMenuBar11.add(jMenu20);

        jMenu21.setText("Edit");
        jMenuBar11.add(jMenu21);

        jMenu22.setText("File");
        jMenuBar12.add(jMenu22);

        jMenu23.setText("Edit");
        jMenuBar12.add(jMenu23);

        jMenu24.setText("File");
        jMenuBar13.add(jMenu24);

        jMenu25.setText("Edit");
        jMenuBar13.add(jMenu25);

        jMenu26.setText("File");
        jMenuBar14.add(jMenu26);

        jMenu27.setText("Edit");
        jMenuBar14.add(jMenu27);

        jMenu28.setText("File");
        jMenuBar15.add(jMenu28);

        jMenu29.setText("Edit");
        jMenuBar15.add(jMenu29);

        jMenu30.setText("File");
        jMenuBar16.add(jMenu30);

        jMenu31.setText("Edit");
        jMenuBar16.add(jMenu31);

        jMenu32.setText("File");
        jMenuBar17.add(jMenu32);

        jMenu33.setText("Edit");
        jMenuBar17.add(jMenu33);

        jMenu34.setText("File");
        jMenuBar18.add(jMenu34);

        jMenu35.setText("Edit");
        jMenuBar18.add(jMenu35);

        jMenu36.setText("File");
        jMenuBar18.add(jMenu36);

        jMenu37.setText("Edit");
        jMenuBar18.add(jMenu37);

        jMenu38.setText("File");
        jMenuBar19.add(jMenu38);

        jMenu39.setText("Edit");
        jMenuBar19.add(jMenu39);

        jMenu40.setText("File");
        jMenuBar20.add(jMenu40);

        jMenu41.setText("Edit");
        jMenuBar20.add(jMenu41);

        jMenu42.setText("File");
        jMenuBar21.add(jMenu42);

        jMenu43.setText("Edit");
        jMenuBar21.add(jMenu43);

        jMenu44.setText("File");
        jMenuBar22.add(jMenu44);

        jMenu45.setText("Edit");
        jMenuBar22.add(jMenu45);

        jMenu46.setText("File");
        jMenuBar23.add(jMenu46);

        jMenu47.setText("Edit");
        jMenuBar23.add(jMenu47);

        jMenu48.setText("File");
        jMenuBar24.add(jMenu48);

        jMenu49.setText("Edit");
        jMenuBar24.add(jMenu49);

        jMenu50.setText("File");
        jMenuBar25.add(jMenu50);

        jMenu51.setText("Edit");
        jMenuBar25.add(jMenu51);

        jMenu52.setText("File");
        jMenuBar26.add(jMenu52);

        jMenu53.setText("Edit");
        jMenuBar26.add(jMenu53);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jButton2.setText("Add Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TextFieldAccountNumber1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAccountNumber1.setText("Enter Account Number");
        TextFieldAccountNumber1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber1FocusLost(evt);
            }
        });
        TextFieldAccountNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccountNumber1ActionPerformed(evt);
            }
        });

        jTextFieldAccountName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAccountName.setText("Enter Account Holder's Name");
        jTextFieldAccountName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAccountNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAccountNameFocusLost(evt);
            }
        });
        jTextFieldAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountNameActionPerformed(evt);
            }
        });

        jTextFieldAccountAdress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAccountAdress.setText("Enter Account Holder's Address");
        jTextFieldAccountAdress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAccountAdressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAccountAdressFocusLost(evt);
            }
        });
        jTextFieldAccountAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountAdressActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Account");

        jButton3.setText("Close Account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextFieldAccountNumber2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAccountNumber2.setText("Enter Account Number");
        jTextFieldAccountNumber2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAccountNumber2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAccountNumber2FocusLost(evt);
            }
        });
        jTextFieldAccountNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountNumber2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Close Account");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Print Previous Withdraws");

        jButton4.setText("print Accounts Information");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Print All Accounts");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Print Previous Transactions");

        jButton5.setText("print Transactions");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("print Withdraws");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        TextFieldAccountNumber4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAccountNumber4.setText("Enter Account Number");
        TextFieldAccountNumber4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber4FocusLost(evt);
            }
        });
        TextFieldAccountNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccountNumber4ActionPerformed(evt);
            }
        });

        TextFieldAccountNumber3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAccountNumber3.setText("Enter Account Number");
        TextFieldAccountNumber3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber3FocusLost(evt);
            }
        });
        TextFieldAccountNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccountNumber3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Transaction");

        jTextFieldTransaction1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTransaction1.setText("Enter New Transaction");
        jTextFieldTransaction1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTransaction1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTransaction1FocusLost(evt);
            }
        });
        jTextFieldTransaction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransaction1ActionPerformed(evt);
            }
        });

        jButton7.setText("add Transaction");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        TextFieldAccountNumber5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAccountNumber5.setText("Enter Account Number");
        TextFieldAccountNumber5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber5FocusLost(evt);
            }
        });
        TextFieldAccountNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccountNumber5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bank Account Control Software");

        jButton1.setText("clear input fields");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldAccountNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jButton5)))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jButton6))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldAccountNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldAccountNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(jButton3)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                                .addComponent(jTextFieldAccountNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextFieldAccountNumber5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTransaction1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAccountAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(38, 38, 38))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(TextFieldAccountNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAccountAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextFieldAccountNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAccountNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jTextFieldTransaction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldAccountNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldAccountNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldAccountNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAccountNumber1ActionPerformed

    private void jTextFieldAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountNameActionPerformed

    private void jTextFieldAccountAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountAdressActionPerformed

    private void jTextFieldAccountNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountNumber2ActionPerformed

    //button to add an account
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //error detection for entering account number 
        //to make sure a LONG isnt enetred the length of an account number
        //was limited to 8 chars to resolve this possible error
        if (TextFieldAccountNumber1.getText().length() > 8) {
            JOptionPane.showMessageDialog(null, "Account Number is Too large Any account number must be 8 Digits ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else if (TextFieldAccountNumber1.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Account Number is Too SMALL Any account number must be 8 Digits ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else {
            AccountMain newAccount = new AccountMain(Integer.parseInt(TextFieldAccountNumber1.getText()), jTextFieldAccountName.getText(), jTextFieldAccountAdress.getText());
            AccountListApp.Accounts.add(newAccount);

            resetAllTextFields();
            String infoMessage = AccountListApp.Accounts.get(AccountListApp.Accounts.size() - 1).printAllAccounts2();
            String titleBar = "Account Sucessfully Added";

            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AccountListApp.PrintAllAccounts2();

        String infoMessage = AccountListApp.PrintAllAccounts2();
        String titleBar = "Full List Of Accounts";

        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
        resetAllTextFields();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TextFieldAccountNumber1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber1FocusGained
        // TODO add your handling code here:
        if (TextFieldAccountNumber1.getText().equals("Enter Account Number")) {
            TextFieldAccountNumber1.setText("");
        }
    }//GEN-LAST:event_TextFieldAccountNumber1FocusGained

    private void TextFieldAccountNumber1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber1FocusLost
        // TODO add your handling code here:
        if (TextFieldAccountNumber1.getText().equals("")) {
            TextFieldAccountNumber1.setText("Enter Account Number");
        }
    }//GEN-LAST:event_TextFieldAccountNumber1FocusLost

    private void jTextFieldAccountNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountNameFocusGained
        // TODO add your handling code here:
        if (jTextFieldAccountName.getText().equals("Enter Account Holder's Name")) {
            jTextFieldAccountName.setText("");
        }
    }//GEN-LAST:event_jTextFieldAccountNameFocusGained

    private void jTextFieldAccountNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountNameFocusLost
        // TODO add your handling code here:
        if (jTextFieldAccountName.getText().equals("")) {
            jTextFieldAccountName.setText("Enter Account Holder's Name");
        }
    }//GEN-LAST:event_jTextFieldAccountNameFocusLost

    private void jTextFieldAccountAdressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountAdressFocusGained
        // TODO add your handling code here:
        if (jTextFieldAccountAdress.getText().equals("Enter Account Holder's Address")) {
            jTextFieldAccountAdress.setText("");
        }
    }//GEN-LAST:event_jTextFieldAccountAdressFocusGained

    private void jTextFieldAccountAdressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountAdressFocusLost
        // TODO add your handling code here:
        if (jTextFieldAccountAdress.getText().equals("")) {
            jTextFieldAccountAdress.setText("Enter Account Holder's Address");
        }
    }//GEN-LAST:event_jTextFieldAccountAdressFocusLost

    private void jTextFieldAccountNumber2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountNumber2FocusGained
        // TODO add your handling code here:
        if (jTextFieldAccountNumber2.getText().equals("Enter Account Number")) {
            jTextFieldAccountNumber2.setText("");
        }
    }//GEN-LAST:event_jTextFieldAccountNumber2FocusGained

    private void jTextFieldAccountNumber2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountNumber2FocusLost
        // TODO add your handling code here:
        if (jTextFieldAccountNumber2.getText().equals("")) {
            jTextFieldAccountNumber2.setText("Enter Account Number");
        }
    }//GEN-LAST:event_jTextFieldAccountNumber2FocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (AccountListApp.Accounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no Accounts on the system", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else if (AccountListApp.checkAccount(jTextFieldAccountNumber2.getText())) {

            AccountListApp.closeAccount(jTextFieldAccountNumber2.getText());
            String titleBar = "Account Sucessfully Closed";
            String infoMessage = "Account " + jTextFieldAccountNumber2.getText() + "Sucessfully closed";
            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
            resetAllTextFields();
        } else {
            JOptionPane.showMessageDialog(null, "There are no Accounts matching the Account number you have entered\n Try Again. ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if (AccountListApp.Accounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no Accounts on the system", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else if (AccountListApp.checkAccount(TextFieldAccountNumber3.getText())) {
            String titleBar = TextFieldAccountNumber3.getText() + " Incoming Payments ";
            String infoMessage = AccountListApp.printAllTransactions2(TextFieldAccountNumber3.getText());

            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "There are no Accounts matching the Account number you have entered\n Try Again. ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        }
        resetAllTextFields();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void TextFieldAccountNumber4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber4FocusGained
        // TODO add your handling code here:
        if (TextFieldAccountNumber4.getText().equals("Enter Account Number")) {
            TextFieldAccountNumber4.setText("");
        }
    }//GEN-LAST:event_TextFieldAccountNumber4FocusGained

    private void TextFieldAccountNumber4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber4FocusLost
        // TODO add your handling code here:
        if (TextFieldAccountNumber4.getText().equals("")) {
            TextFieldAccountNumber4.setText("Enter Account Number");
        }
    }//GEN-LAST:event_TextFieldAccountNumber4FocusLost

    private void TextFieldAccountNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAccountNumber4ActionPerformed

    private void TextFieldAccountNumber3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber3FocusGained
        // TODO add your handling code here:
        if (TextFieldAccountNumber3.getText().equals("Enter Account Number")) {
            TextFieldAccountNumber3.setText("");
        }
    }//GEN-LAST:event_TextFieldAccountNumber3FocusGained

    private void TextFieldAccountNumber3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber3FocusLost
        // TODO add your handling code here:
        if (TextFieldAccountNumber3.getText().equals("")) {
            TextFieldAccountNumber3.setText("Enter Account Number");
        }
    }//GEN-LAST:event_TextFieldAccountNumber3FocusLost

    private void TextFieldAccountNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TextFieldAccountNumber3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        if (AccountListApp.Accounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no Accounts on the system", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else if (AccountListApp.checkAccount(TextFieldAccountNumber4.getText())) {
            String titleBar = TextFieldAccountNumber4.getText() + " OutGoing Payments ";
            String infoMessage = AccountListApp.printAllWithdraws2(TextFieldAccountNumber4.getText());

            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
            resetAllTextFields();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextFieldTransaction1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTransaction1FocusGained
        // TODO add your handling code here:
        if (jTextFieldTransaction1.getText().equals("Enter New Transaction")) {
            jTextFieldTransaction1.setText("");
        }
    }//GEN-LAST:event_jTextFieldTransaction1FocusGained

    private void jTextFieldTransaction1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTransaction1FocusLost
        // TODO add your handling code here:
        if (jTextFieldTransaction1.getText().equals("")) {
            jTextFieldTransaction1.setText("Enter Account Number");
        }
    }//GEN-LAST:event_jTextFieldTransaction1FocusLost

    private void jTextFieldTransaction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransaction1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTransaction1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        if (AccountListApp.Accounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no Accounts on the system", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else if (AccountListApp.checkAccount(TextFieldAccountNumber5.getText())) {
            AccountListApp.addTransaction(TextFieldAccountNumber5.getText(), Double.parseDouble(jTextFieldTransaction1.getText()));

            String titleBar = "Transaction Successfully Added";
            String infoMessage = "Account: " + TextFieldAccountNumber5.getText() + "\n" + "Transaction : " + jTextFieldTransaction1.getText() + "\n" + "**SUCESS**";
            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
            resetAllTextFields();
        } else {
            JOptionPane.showMessageDialog(null, "There are no Accounts matching the Account number you have entered\n Try Again. ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void TextFieldAccountNumber5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber5FocusGained
        // TODO add your handling code here:
        if (TextFieldAccountNumber5.getText().equals("Enter Account Number")) {
            TextFieldAccountNumber5.setText("");
        }
    }//GEN-LAST:event_TextFieldAccountNumber5FocusGained

    private void TextFieldAccountNumber5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber5FocusLost
        // TODO add your handling code here:
        if (TextFieldAccountNumber5.getText().equals("")) {
            TextFieldAccountNumber5.setText("Enter Account Number");
        }
    }//GEN-LAST:event_TextFieldAccountNumber5FocusLost

    private void TextFieldAccountNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAccountNumber5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetAllTextFields();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldAccountNumber1;
    private javax.swing.JTextField TextFieldAccountNumber3;
    private javax.swing.JTextField TextFieldAccountNumber4;
    private javax.swing.JTextField TextFieldAccountNumber5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar12;
    private javax.swing.JMenuBar jMenuBar13;
    private javax.swing.JMenuBar jMenuBar14;
    private javax.swing.JMenuBar jMenuBar15;
    private javax.swing.JMenuBar jMenuBar16;
    private javax.swing.JMenuBar jMenuBar17;
    private javax.swing.JMenuBar jMenuBar18;
    private javax.swing.JMenuBar jMenuBar19;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar20;
    private javax.swing.JMenuBar jMenuBar21;
    private javax.swing.JMenuBar jMenuBar22;
    private javax.swing.JMenuBar jMenuBar23;
    private javax.swing.JMenuBar jMenuBar24;
    private javax.swing.JMenuBar jMenuBar25;
    private javax.swing.JMenuBar jMenuBar26;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextFieldAccountAdress;
    private javax.swing.JTextField jTextFieldAccountName;
    private javax.swing.JTextField jTextFieldAccountNumber2;
    private javax.swing.JTextField jTextFieldTransaction1;
    // End of variables declaration//GEN-END:variables

    public void resetAllTextFields() {
        TextFieldAccountNumber1.setText("Enter Account Number");
        jTextFieldAccountName.setText("Enter Account Holder's Name");
        jTextFieldAccountAdress.setText("Enter Account Holder's Address");
        jTextFieldAccountNumber2.setText("Enter Account Number");
        TextFieldAccountNumber3.setText("Enter Account Number");
        TextFieldAccountNumber4.setText("Enter Account Number");
        TextFieldAccountNumber5.setText("Enter Account Number");
        jTextFieldTransaction1.setText("Enter New Transaction");

    }

}
