/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ryansPC
 */
import javax.swing.*;

public class addAccount extends javax.swing.JFrame {

    /**
     * Creates new form addAccount
     */
    public addAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        TextFieldAccountNumber1 = new javax.swing.JTextField();
        jTextFieldAccountName = new javax.swing.JTextField();
        jTextFieldAccountAdress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButton2.setText("Add Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TextFieldAccountNumber1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAccountNumber1.setText("Enter Account Number");
        TextFieldAccountNumber1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber1FocusLost(evt);
            }
        });
        TextFieldAccountNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccountNumber1ActionPerformed(evt);
            }
        });

        jTextFieldAccountName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAccountName.setText("Enter Account Holder's Name");
        jTextFieldAccountName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAccountNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAccountNameFocusLost(evt);
            }
        });
        jTextFieldAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountNameActionPerformed(evt);
            }
        });

        jTextFieldAccountAdress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAccountAdress.setText("Enter Account Holder's Address");
        jTextFieldAccountAdress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAccountAdressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAccountAdressFocusLost(evt);
            }
        });
        jTextFieldAccountAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountAdressActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Add A New Account");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldAccountNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAccountAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TextFieldAccountNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldAccountAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //error detection for entering account number
        //to make sure a LONG isnt enetred the length of an account number
        //was limited to 8 chars to resolve this possible error
        if (TextFieldAccountNumber1.getText().length() > 8) {
            JOptionPane.showMessageDialog(null, "Account Number is Too large Any account number must be 8 Digits ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else if (TextFieldAccountNumber1.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Account Number is Too SMALL Any account number must be 8 Digits ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else {
            AccountMain newAccount = new AccountMain(Integer.parseInt(TextFieldAccountNumber1.getText()), jTextFieldAccountName.getText(), jTextFieldAccountAdress.getText());
            AccountListApp.Accounts.add(newAccount);

            resetAllTextFields();
            String infoMessage = AccountListApp.Accounts.get(AccountListApp.Accounts.size() - 1).printAllAccounts2();
            String titleBar = "Account Sucessfully Added";

            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextFieldAccountNumber1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber1FocusGained
        // TODO add your handling code here:
        if (TextFieldAccountNumber1.getText().equals("Enter Account Number")) {
            TextFieldAccountNumber1.setText("");
        }
    }//GEN-LAST:event_TextFieldAccountNumber1FocusGained

    private void TextFieldAccountNumber1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber1FocusLost
        // TODO add your handling code here:
        if (TextFieldAccountNumber1.getText().equals("")) {
            TextFieldAccountNumber1.setText("Enter Account Number");
        }
    }//GEN-LAST:event_TextFieldAccountNumber1FocusLost

    private void TextFieldAccountNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAccountNumber1ActionPerformed

    private void jTextFieldAccountNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountNameFocusGained
        // TODO add your handling code here:
        if (jTextFieldAccountName.getText().equals("Enter Account Holder's Name")) {
            jTextFieldAccountName.setText("");
        }
    }//GEN-LAST:event_jTextFieldAccountNameFocusGained

    private void jTextFieldAccountNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountNameFocusLost
        // TODO add your handling code here:
        if (jTextFieldAccountName.getText().equals("")) {
            jTextFieldAccountName.setText("Enter Account Holder's Name");
        }
    }//GEN-LAST:event_jTextFieldAccountNameFocusLost

    private void jTextFieldAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountNameActionPerformed

    private void jTextFieldAccountAdressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountAdressFocusGained
        // TODO add your handling code here:
        if (jTextFieldAccountAdress.getText().equals("Enter Account Holder's Address")) {
            jTextFieldAccountAdress.setText("");
        }
    }//GEN-LAST:event_jTextFieldAccountAdressFocusGained

    private void jTextFieldAccountAdressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccountAdressFocusLost
        // TODO add your handling code here:
        if (jTextFieldAccountAdress.getText().equals("")) {
            jTextFieldAccountAdress.setText("Enter Account Holder's Address");
        }
    }//GEN-LAST:event_jTextFieldAccountAdressFocusLost

    private void jTextFieldAccountAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountAdressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAccount().setVisible(true);
            }
        });
    }
        public void resetAllTextFields() {
        TextFieldAccountNumber1.setText("Enter Account Number");
        jTextFieldAccountName.setText("Enter Account Holder's Name");
        jTextFieldAccountAdress.setText("Enter Account Holder's Address");
//        jTextFieldAccountNumber2.setText("Enter Account Number");
//        TextFieldAccountNumber3.setText("Enter Account Number");
//        TextFieldAccountNumber4.setText("Enter Account Number");
//        TextFieldAccountNumber5.setText("Enter Account Number");
//        jTextFieldTransaction1.setText("Enter New Transaction");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldAccountNumber1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextFieldAccountAdress;
    private javax.swing.JTextField jTextFieldAccountName;
    // End of variables declaration//GEN-END:variables
}
