/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ryansPC
 */
import javax.swing.*;

public class addTransaction extends javax.swing.JFrame {

    /**
     * Creates new form addTransaction
     */
    public addTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTransaction1 = new javax.swing.JTextField();
        TextFieldAccountNumber5 = new javax.swing.JTextField();

        jButton7.setText("add Transaction");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Transaction");

        jTextFieldTransaction1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTransaction1.setText("Enter New Transaction");
        jTextFieldTransaction1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTransaction1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTransaction1FocusLost(evt);
            }
        });
        jTextFieldTransaction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransaction1ActionPerformed(evt);
            }
        });

        TextFieldAccountNumber5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAccountNumber5.setText("Enter Account Number");
        TextFieldAccountNumber5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber5FocusLost(evt);
            }
        });
        TextFieldAccountNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccountNumber5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TextFieldAccountNumber5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTransaction1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(TextFieldAccountNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTransaction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton7)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldTransaction1.getText().matches("-?\\d+(\\.\\d+)?")){
            if (AccountListApp.Accounts.isEmpty()) {
                JOptionPane.showMessageDialog(null, "There are no Accounts on the system", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
            } else if (AccountListApp.checkAccount(TextFieldAccountNumber5.getText())) {
                AccountListApp.addTransaction(TextFieldAccountNumber5.getText(), Double.parseDouble(jTextFieldTransaction1.getText()));

                String titleBar = "Transaction Successfully Added";
                String infoMessage = "Account: " + TextFieldAccountNumber5.getText() + "\n" + "Transaction : " + jTextFieldTransaction1.getText() + "\n" + "**SUCESS**";
                JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
                resetAllTextFields();
            } else {
                JOptionPane.showMessageDialog(null, "There are no Accounts matching the Account number you have entered\n Try Again. ", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "You have entered an invalid amount", "INVALID AMOUNT ENTERED", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextFieldTransaction1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTransaction1FocusGained
        // TODO add your handling code here:
        if (jTextFieldTransaction1.getText().equals("Enter New Transaction")) {
            jTextFieldTransaction1.setText("");
        }
    }//GEN-LAST:event_jTextFieldTransaction1FocusGained

    private void jTextFieldTransaction1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTransaction1FocusLost
        // TODO add your handling code here:
        if (jTextFieldTransaction1.getText().equals("")) {
            jTextFieldTransaction1.setText("Enter Account Number");
        }
    }//GEN-LAST:event_jTextFieldTransaction1FocusLost

    private void jTextFieldTransaction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransaction1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTransaction1ActionPerformed

    private void TextFieldAccountNumber5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber5FocusGained
        // TODO add your handling code here:
        if (TextFieldAccountNumber5.getText().equals("Enter Account Number")) {
            TextFieldAccountNumber5.setText("");
        }
    }//GEN-LAST:event_TextFieldAccountNumber5FocusGained

    private void TextFieldAccountNumber5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber5FocusLost
        // TODO add your handling code here:
        if (TextFieldAccountNumber5.getText().equals("")) {
            TextFieldAccountNumber5.setText("Enter Account Number");
        }
    }//GEN-LAST:event_TextFieldAccountNumber5FocusLost

    private void TextFieldAccountNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAccountNumber5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTransaction().setVisible(true);
            }
        });
    }
    
    //resets the text fields so later use
    public void resetAllTextFields() {

        TextFieldAccountNumber5.setText("Enter Account Number");
        jTextFieldTransaction1.setText("Enter New Transaction");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldAccountNumber5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldTransaction1;
    // End of variables declaration//GEN-END:variables
}
