/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ryansPC
 */
import javax.swing.*;

public class withdraws extends javax.swing.JFrame {

    /**
     * Creates new form withdraws
     */
    public withdraws() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        TextFieldAccountNumber4 = new javax.swing.JTextField();

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Print Previous Withdraws");

        jButton6.setText("print Withdraws");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        TextFieldAccountNumber4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAccountNumber4.setText("Enter Account Number");
        TextFieldAccountNumber4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldAccountNumber4FocusLost(evt);
            }
        });
        TextFieldAccountNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccountNumber4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldAccountNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextFieldAccountNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        if (AccountListApp.Accounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no Accounts on the system", "INVALID ACCOUNT NUMBER", JOptionPane.WARNING_MESSAGE);
        } else if (AccountListApp.checkAccount(TextFieldAccountNumber4.getText())) {
            String titleBar = TextFieldAccountNumber4.getText() + " OutGoing Payments ";
            String infoMessage = AccountListApp.printAllWithdraws2(TextFieldAccountNumber4.getText());

            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
            resetAllTextFields();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TextFieldAccountNumber4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber4FocusGained
        // TODO add your handling code here:
        if (TextFieldAccountNumber4.getText().equals("Enter Account Number")) {
            TextFieldAccountNumber4.setText("");
        }
    }//GEN-LAST:event_TextFieldAccountNumber4FocusGained

    private void TextFieldAccountNumber4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber4FocusLost
        // TODO add your handling code here:
        if (TextFieldAccountNumber4.getText().equals("")) {
            TextFieldAccountNumber4.setText("Enter Account Number");
        }
    }//GEN-LAST:event_TextFieldAccountNumber4FocusLost

    private void TextFieldAccountNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccountNumber4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAccountNumber4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdraws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdraws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdraws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdraws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdraws().setVisible(true);
            }
        });
    }

    //resets the text fields so later use
    public void resetAllTextFields() {

        TextFieldAccountNumber4.setText("Enter Account Number");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldAccountNumber4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
